
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author choy
 */
class Node{
        int d;
        Node next=null;
        
        public Node(int data){
            d = data;
        }
    }

class LinkedList{
    Node first=null;
    
    public void addFirst(int data){
        Node node = new Node(data);
        if(first==null)
            first=node;
        else{
            node.next=first;
            first=node;
        }
    }
//    public void showdata(){
//        return last.data;
//    }
    
    public void removeFirst(){
            first=first.next;
        }
    
    public void delete(int value){
        Node temp=first;
        Node temp1=first;
        
        if(first.d==value){
            first=temp.next;
            temp=null;
        }
        else{
            while(temp.next!=null){
                if(temp.next.d==value){
                    break;
                }
                temp = temp.next;
                if(temp.next.next==null){
                   temp1=temp; 
                }
            }
            if(temp.next == null&&temp.d == value){
                temp1.next=null;
                temp=temp1;
            }
            else{
                Node current=temp;
                Node center=temp.next;
                current.next=center.next;
                center.next=null;
            }
        }
    }

    
    public String Display(){
        Node current=first;
        String output = "Playing song No: ---> ";
        while(current!=null)
        {
            output += current.d;
            if(current.next != null)
                output += " ---> ";
            current=current.next;
        }
        
        return output;
    }
}
public class LinkedListGUIForm extends javax.swing.JFrame {
        LinkedList li = new LinkedList();
    /**
     * Creates new form LinkedListGUIForm
     */
    public LinkedListGUIForm() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        insertText = new javax.swing.JTextField();
        displayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayLL = new javax.swing.JTextArea();
        Delete = new javax.swing.JButton();
        deleteText1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.jpg"))); // NOI18N
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        jPanel2.add(insertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 30, 30));

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/previous.jpg"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 30, 30));

        insertText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTextActionPerformed(evt);
            }
        });
        jPanel2.add(insertText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 64, -1));

        displayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });
        jPanel2.add(displayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 50, 50));

        displayLL.setEditable(false);
        displayLL.setBackground(new java.awt.Color(0, 0, 0));
        displayLL.setColumns(20);
        displayLL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        displayLL.setForeground(new java.awt.Color(204, 153, 0));
        displayLL.setRows(5);
        jScrollPane1.setViewportView(displayLL);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 250, 70));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 50, 50));
        jPanel2.add(deleteText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 66, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music player.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 420, 340));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Advance Music Player");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertTextActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        li.addFirst(Integer.parseInt(insertText.getText()));
    }//GEN-LAST:event_insertButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        li.removeFirst();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        // TODO add your handling code here:
        displayLL.setText(li.Display());
    }//GEN-LAST:event_displayButtonActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        li.delete(Integer.parseInt(deleteText1.getText()));
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkedListGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkedListGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkedListGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkedListGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkedListGUIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField deleteText1;
    private javax.swing.JButton displayButton;
    private javax.swing.JTextArea displayLL;
    private javax.swing.JButton insertButton;
    private javax.swing.JTextField insertText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
